routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('home1');
//    //return view('welcome');
//});

Route::get('/', 'KentekenController@home');
Route::post('/kenteken/make-pdf', 'KentekenController@makePDF');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => ['permission:admin']], function () {
    Route::resource('users', 'UserController');
    Route::resource('goods', 'GoodController');
    Route::resource('orders', 'OrderController');

    Route::get('statistics/index', 'StatisticsController@index');
    Route::get('statistics/analytics', 'StatisticsController@analytics');
    Route::get('statistics/traffic', 'StatisticsController@traffic');
});

Route::get('/buy', 'BuyController@buy');
Route::get('/buy/cart', 'BuyController@cart');
Route::get('/buy/add-to-cart/{id}', 'BuyController@addToCart');
Route::post('/buy/confirm', 'BuyController@confirm');

Route::get('/pdf', 'KentekenController@pdf');

Route::get('/kenteken/buy-pdf', 'KentekenController@buyPDF');
Route::get('/kenteken/pay-pdf', 'KentekenController@payPDF');
Route::get('/kenteken/show-pdf', 'KentekenController@showPDF');
Route::get('/kenteken/cabinet', 'KentekenController@cabinet');

Route::post('/kenteken/pdfSubmit', 'KentekenController@pdfSubmit');
Route::post('/kenteken/submitBuyPDF', 'KentekenController@submitBuyPDF');
Route::post('/kenteken/submitPayPDF', 'KentekenController@submitPayPDF');
Route::post('/kenteken/show-short-pdf', 'KentekenController@showShortPDF');
Route::get('/kenteken/confirm-mollie', 'KentekenController@confirmMollie');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use Notifiable;
    use HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'credits', 'bought', 'credits_add', 'mollie_id'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function scopeSearchByName($query, $keyword)
    {
        if ($keyword != '') {
            $query->where(function ($query) use ($keyword) {
                $query->where("name", "LIKE", "%$keyword%");
            });
        }
        return $query;
    }

    public function scopeSearchByEmail($query, $keyword)
    {
        if ($keyword != '') {
            $query->where(function ($query) use ($keyword) {
                $query->where("email", "LIKE", "%$keyword%");
            });
        }
        return $query;
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Spatie\Permission\Models\Role;
use App\User;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    public function __construct()
    {
        $this->middleware(['auth']);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::searchByName(request()->searchName)
            ->searchByEmail(request()->searchEmail)
            ->orderBy('id', 'desc')->paginate(24);

        return view('users.index', [
            'users' => $users,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $roles = Role::orderBy('id', 'desc')->get();

        return view('users.form', [
            'user' => new User(),
            'roles' => $roles
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|string|max:255',
            'email' => 'required|string|email|max:255|unique:users',
            'password' => 'required|string|min:6',
        ]);

        $user = new User($request->all());
        $user->password = Hash::make($request->password);
        $user->save();

        $roles = $request['roles']; //Retrieving the roles field
        //Checking if a role was selected
        if (isset($roles)) {
            foreach ($roles as $role) {
                $role_r = Role::where('id', '=', $role)->firstOrFail();
                $user->assignRole($role_r); //Assigning role to user
            }
        }

        return redirect()->action('UserController@index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = User::find($id);

        return view('users.show', [
            'user' => $user
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::find($id);
        $roles = Role::orderBy('id', 'desc')->get();
        $checkedRoles = [];
        foreach ($user->roles as $role) {
            $checkedRoles[] = $role->id;
        }

        return view('users.edit', [
            'user' => $user,
            'roles' => $roles,
            'checkedRoles' => $checkedRoles
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required|string|max:255',
            'email' => 'required|string|email|max:255|unique:users,email,'.$id,
        ]);

        $user = User::find($id);
        $user->update($request->except('password'));
        if ($request->password != '') {
            $user->password = Hash::make($request->password);;
        }

        $user->save();

        $roles = $request['roles']; //Retreive all roles
        if (isset($roles)) {
            $user->roles()->sync($roles);  //If one or more role is selected associate user to roles
        }
        else {
            $user->roles()->detach(); //If no role is selected remove exisiting role associated to a user
        }

        return redirect()->action('UserController@index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::find($id);
        $user->delete();
        return redirect()->back();
    }
}

resources/views/users/edit.blade.php
@extends('adminlte::page')

@section('title', 'Users')

@section('content_header')
    <h1>Users</h1>
@stop

@section('content')
    <div class="box box-primary">
        @if ($errors->any())
            <ul class="errors">
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        @endif
        <div class="box-header with-border">
            <h3 class="box-title">{{isset($user->id) ? 'Update' : 'Create'}}</h3>
        </div>
        <form action="{{isset($user->id) ? route('users.update', $user->id) : route('users.index')}}" method="post" enctype="multipart/form-data">
            {{ csrf_field() }}
            {{ method_field(isset($user->id) ? 'PUT' : 'POST') }}
            <div class="box-body">
                <div class="form-group">
                    <label for="name">Name</label>
                    <input class="form-control" id="name" name="name" value="{{ old('name', $user->name) }}"/>
                </div>
                <div class="form-group">
                    <label for="email">Email</label>
                    <input class="form-control" type="email" id="email" name="email" value="{{ old('email', $user->email) }}"/>
                </div>
                <div class="form-group">
                    <label for="password">Password</label>
                    <input class="form-control" type="password" id="password" name="password" />
                </div>
                <div class="form-group">
                    @foreach($roles as $role)
                        <input type="checkbox"
                               name="roles[]"
                               value="{{$role->id}}"
                                {{ in_array($role->id, $checkedRoles) ? 'checked': '' }}> <label>{{$role->name}}</label>
                    @endforeach
                </div>
            </div>
            <!-- /.box-body -->

            <div class="box-footer">
                <button type="submit" class="btn btn-primary">Update</button>
                <a href="{{url('/users')}}" class="btn btn-default">Cancel</a>
            </div>
        </form>
    </div>

@stop

resources/views/users/form.blade.php
@extends('adminlte::page')

@section('title', 'Users')

@section('content_header')
    <h1>Users</h1>
@stop

@section('content')
    <div class="box box-primary">
        @if ($errors->any())
            <ul class="errors">
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        @endif
        <div class="box-header with-border">
            <h3 class="box-title">{{isset($user->id) ? 'Update' : 'Create'}}</h3>
        </div>
        <form action="{{isset($user->id) ? route('users.update', $user->id) : route('users.index')}}" method="post" enctype="multipart/form-data">
            {{ csrf_field() }}
            {{ method_field(isset($user->id) ? 'PUT' : 'POST') }}
            <div class="box-body">
                <div class="form-group">
                    <label for="name">Name</label>
                    <input class="form-control" id="name" name="name" value="{{ old('name', $user->name) }}"/>
                </div>
                <div class="form-group">
                    <label for="email">Email</label>
                    <input class="form-control" type="email" id="email" name="email" value="{{ old('email', $user->email) }}"/>
                </div>
                <div class="form-group">
                    <label for="password">Password</label>
                    <input class="form-control" type="password" id="password" name="password" value="{{ old('password', $user->password) }}"/>
                </div>
                <div class="form-group">
                    @foreach($roles as $role)
                        <input type="checkbox"
                               name="roles[]"
                               value="{{$role->id}}" }}> <label>{{$role->name}}</label>
                    @endforeach
                </div>
            </div>
            <!-- /.box-body -->

            <div class="box-footer">
                <button type="submit" class="btn btn-primary">Create</button>
                <a href="{{url('/users')}}" class="btn btn-default">Cancel</a>
            </div>
        </form>
    </div>

@stop

resources/views/users/index.blade.php
@extends('adminlte::page')

@section('title', 'Users')

@section('content_header')
    <h1>Users</h1>
@stop

@section('content')
    <section class="content">
        <a href="{{'users/create'}}" class="btn btn-primary" >Create</a>
        <br/><br/>
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title">Users</h3>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <div id="example2_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
                            <div class="row"><div class="col-sm-6"></div><div class="col-sm-6"></div></div><div class="row">
                                <div class="col-sm-12">
                                    <table id="example2" class="table table-bordered table-hover table-striped dataTable" role="grid" aria-describedby="example2_info">
                                        <thead>
                                        <tr role="row">
                                            <th>Name</th>
                                            <th>Email</th>
                                            <th>Roles</th>
                                            <th>Actions</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        <tr>
                                            <form class="form-inline search" id="search" method="get" action="/{{ Request::path() }}">
                                                <td>
                                                    <input type="text" class="form-control" name="searchName" autocomplete="off" placeholder="Name" value="{{Request::input('searchName')}}">
                                                </td>
                                                <td>
                                                    <input type="text" class="form-control" name="searchEmail" autocomplete="off" placeholder="Email" value="{{Request::input('searchEmail')}}">
                                                </td>
                                                <td></td>
                                                <td></td>
                                                <input type="submit" hidden>
                                            </form>
                                        </tr>
                                        @foreach($users as $user)
                                            <tr role="row" class="odd">
                                                <td><a href="{{ url('users/' . $user->id) }}">{{$user->name}}</a></td>
                                                <td>{{$user->email}}</td>
                                                <td>{{$user->roles()->pluck('name')->implode(', ')}}</td>
                                                <td width="240">
                                                    <a href="{{ url('users/' . $user->id) }}" class="btn btn-success btn-sm"><i class="fa fa-edit mr-2" aria-hidden="true"></i>View</a>
                                                    <a href="{{ url('users/' . $user->id . '/edit') }}" class="btn btn-primary btn-sm"><i class="fa fa-edit mr-2" aria-hidden="true"></i>Update</a>
                                                    <button type="button" class="btn btn-secondary btn-sm" data-toggle="modal" data-target="#delete_{{$user->id}}"><i class="fa fa-trash mr-2" aria-hidden="true"></i>Delete</button>

                                                    <div class="modal fade" id="delete_{{$user->id}}" tabindex="-1" role="dialog" aria-labelledby="modal_{{$user->id}}" aria-hidden="true">
                                                        <div class="modal-dialog" role="document">
                                                            <div class="modal-content">
                                                                <div class="modal-header">
                                                                    <h5 class="modal-title" id="modal_{{$user->id}}">Confirm</h5>
                                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                                        <span aria-hidden="true">&times;</span>
                                                                    </button>
                                                                </div>
                                                                <div class="modal-body">
                                                                    <p>Are you sure you want to delete this item?</p>
                                                                </div>
                                                                <div class="modal-footer">
                                                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                                                                    <form action='{{ route('users.destroy', $user->id) }}' method="POST" style="display: inline">
                                                                        <input type="hidden" name="_method" value="DELETE">
                                                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                                                        <button type="submit" class="btn btn-danger" style="margin-right: 4px">Confirm</button>
                                                                    </form>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </td>
                                            </tr>
                                        @endforeach
                                        </tbody>
                                    </table>
                                    {{$users
                                        ->appends([
                                            'searchName' => Request::get('searchName'),
                                            'searchEmail' => Request::get('searchEmail'),
                                        ])
                                        ->links()}}
                                </div>
                            </div>
                        </div>
                        <!-- /.box-body -->
                    </div>
                    <!-- /.box -->

                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
    </section>

@stop

resources/views/users/show.blade.php
@extends('adminlte::page')

@section('title', 'Users')

@section('content_header')
    <h1>Users</h1>
@stop

@section('content')
    <div class="box">
        <div class="box-header with-border">
            <h3 class="box-title">{{$user->name}}</h3>
            <a href="{{ url('users/' . $user->id . '/edit') }}" class=""><i class="fa fa-edit mr-2" aria-hidden="true"></i></a>
            <div class="box-body">
                <p>Email: {{$user->email}}</p>
                <p>Roles: {{$user->roles()->pluck('name')->implode(', ')}}</p>
            </div>
        </div>
    </div>
@stop