routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('home1');
//    //return view('welcome');
//});

Route::get('/', 'KentekenController@home');
Route::post('/kenteken/make-pdf', 'KentekenController@makePDF');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => ['permission:admin']], function () {
    Route::resource('users', 'UserController');
    Route::resource('goods', 'GoodController');
    Route::resource('orders', 'OrderController');

    Route::get('statistics/index', 'StatisticsController@index');
    Route::get('statistics/analytics', 'StatisticsController@analytics');
    Route::get('statistics/traffic', 'StatisticsController@traffic');
});

Route::get('/buy', 'BuyController@buy');
Route::get('/buy/cart', 'BuyController@cart');
Route::get('/buy/add-to-cart/{id}', 'BuyController@addToCart');
Route::post('/buy/confirm', 'BuyController@confirm');

Route::get('/pdf', 'KentekenController@pdf');

Route::get('/kenteken/buy-pdf', 'KentekenController@buyPDF');
Route::get('/kenteken/pay-pdf', 'KentekenController@payPDF');
Route::get('/kenteken/show-pdf', 'KentekenController@showPDF');
Route::get('/kenteken/cabinet', 'KentekenController@cabinet');

Route::post('/kenteken/pdfSubmit', 'KentekenController@pdfSubmit');
Route::post('/kenteken/submitBuyPDF', 'KentekenController@submitBuyPDF');
Route::post('/kenteken/submitPayPDF', 'KentekenController@submitPayPDF');
Route::post('/kenteken/show-short-pdf', 'KentekenController@showShortPDF');
Route::get('/kenteken/confirm-mollie', 'KentekenController@confirmMollie');

app/Good.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Good extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'title',
        'description',
        'photo' => 'mimes:jpeg,jpg,png | max:1000',
        'price'
    ];

    protected $dates = [
        'created_at',
        'updated_at'
    ];
}

app/Http/Controllers/GoodController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use App\Good;

class GoodController extends Controller
{
    public function __construct()
    {
        $this->middleware(['auth']);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $goods = Good::orderBy('id', 'desc')->paginate(24);

        return view('goods.index', [
            'goods' => $goods,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('goods.form', [
            'good' => new Good()
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            /*'name' => 'required|string|max:255',
            'email' => 'required|string|email|max:255|unique:users',
            'password' => 'required|string|min:6',*/
        ]);

        $good = new Good($request->all());

        //file storage
        if ($request->hasFile('image')) {
            $good->photo = $request->file('image')->store('public/goods');
            $good->photo = str_replace('public/', '', $good->photo);
        }

        $good->save();

        return redirect()->action('GoodController@index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $good = Good::find($id);

        return view('goods.show', [
            'good' => $good
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $good = Good::find($id);

        return view('goods.form', [
            'good' => $good,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        /*$this->validate($request, [
            'name' => 'required|string|max:255',
            'email' => 'required|string|email|max:255|unique:users,email,'.$id,
        ]);*/

        $good = Good::find($id);
        $good->update($request->all());

        //file replacing
        if ($request->hasFile('image')) {
            if ($good->photo) {
                Storage::delete("public/$good->photo");
            }
            $good->photo = $request->file('image')->store('public/goods');
            $good->photo = str_replace('public/', '', $good->photo);
        }

        $good->save();

        return redirect()->action('GoodController@index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $good= Good::find($id);
        $good->delete();
        return redirect()->back();
    }
}

resources/views/goods/form.blade.php
@extends('adminlte::page')

@section('title', 'Goods')

@section('content_header')
    <h1>Goods</h1>
@stop

@section('content')
    <div class="box box-primary">
        @if ($errors->any())
            <ul class="errors">
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        @endif
        <div class="box-header with-border">
            <h3 class="box-title">{{isset($good->id) ? 'Update' : 'Create'}}</h3>
        </div>
        <form action="{{isset($good->id) ? route('goods.update', $good->id) : route('goods.index')}}" method="post" enctype="multipart/form-data">
            {{ csrf_field() }}
            {{ method_field(isset($good->id) ? 'PUT' : 'POST') }}
            <div class="box-body">
                <div class="form-group">
                    <label for="name">Title</label>
                    <input class="form-control" id="title" name="title" value="{{ old('title', $good->title) }}"/>
                </div>
                <div class="form-group">
                    <label for="name">Description</label>
                    <input class="form-control" id="description" name="description" value="{{ old('description', $good->description) }}"/>
                </div>
                <div class="form-group">
                    <label for="name">Price</label>
                    <input class="form-control" id="price" name="price" value="{{ old('price', $good->price) }}"/>
                </div>
                <div class="form-group">
                    <label for="image">Attach image</label>
                    <input type="file" id="image" name="image">
                </div>
            </div>
            <!-- /.box-body -->

            <div class="box-footer">
                <button type="submit" class="btn btn-primary">Create</button>
                <a href="{{url('/goods')}}" class="btn btn-default">Cancel</a>
            </div>
        </form>
    </div>

@stop

resources/views/goods/index.blade.php
@extends('adminlte::page')

@section('title', 'Goods')

@section('content_header')
    <h1>Goods</h1>
@stop

@section('content')
    <section class="content">
        <a href="{{'goods/create'}}" class="btn btn-primary" >Create</a>
        <br/><br/>
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title">Goods</h3>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <div id="example2_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
                            <div class="row"><div class="col-sm-6"></div><div class="col-sm-6"></div></div><div class="row">
                                <div class="col-sm-12">
                                    <table id="example2" class="table table-bordered table-hover table-striped dataTable" role="grid" aria-describedby="example2_info">
                                        <thead>
                                        <tr role="row">
                                            <th>Name</th>
                                            <th>Description</th>
                                            <th>Photo</th>
                                            <th>Price</th>
                                            <th>Actions</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        {{--<tr>--}}
                                            {{--<form class="form-inline search" id="search" method="get" action="/{{ Request::path() }}">--}}
                                                {{--<td>--}}
                                                    {{--<input type="text" class="form-control" name="searchName" autocomplete="off" placeholder="Name" value="{{Request::input('searchName')}}">--}}
                                                {{--</td>--}}
                                                {{--<td></td>--}}
                                                {{--<td></td>--}}
                                                {{--<td></td>--}}
                                                {{--<td></td>--}}
                                                {{--<input type="submit" hidden>--}}
                                            {{--</form>--}}
                                        {{--</tr>--}}
                                        @foreach($goods as $good)
                                            <tr role="row" class="odd">
                                                <td><a href="{{ url('goods/' . $good->id) }}">{{$good->title}}</a></td>
                                                <td>{{$good->description}}</td>
                                                <td><img src="{{ url('/') }}{{ $good->photo ? Storage::url("$good->photo") : ''}}" alt="picture" class="goods-attached-photo"></td>
                                                <td>{{$good->price}}</td>
                                                <td width="240">
                                                    <a href="{{ url('goods/' . $good->id) }}" class="btn btn-success btn-sm"><i class="fa fa-edit mr-2" aria-hidden="true"></i>View</a>
                                                    <a href="{{ url('goods/' . $good->id . '/edit') }}" class="btn btn-primary btn-sm"><i class="fa fa-edit mr-2" aria-hidden="true"></i>Update</a>
                                                    <button type="button" class="btn btn-secondary btn-sm" data-toggle="modal" data-target="#delete_{{$good->id}}"><i class="fa fa-trash mr-2" aria-hidden="true"></i>Delete</button>

                                                    <div class="modal fade" id="delete_{{$good->id}}" tabindex="-1" role="dialog" aria-labelledby="modal_{{$good->id}}" aria-hidden="true">
                                                        <div class="modal-dialog" role="document">
                                                            <div class="modal-content">
                                                                <div class="modal-header">
                                                                    <h5 class="modal-title" id="modal_{{$good->id}}">Confirm</h5>
                                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                                        <span aria-hidden="true">&times;</span>
                                                                    </button>
                                                                </div>
                                                                <div class="modal-body">
                                                                    <p>Are you sure you want to delete this item?</p>
                                                                </div>
                                                                <div class="modal-footer">
                                                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                                                                    <form action='{{ route('goods.destroy', $good->id) }}' method="POST" style="display: inline">
                                                                        <input type="hidden" name="_method" value="DELETE">
                                                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                                                        <button type="submit" class="btn btn-danger" style="margin-right: 4px">Confirm</button>
                                                                    </form>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </td>
                                            </tr>
                                        @endforeach
                                        </tbody>
                                    </table>
                                    {{$goods
                                        /*->appends([
                                            'searchName' => Request::get('searchName'),
                                            'searchEmail' => Request::get('searchEmail'),
                                        ])*/
                                        ->links()}}
                                </div>
                            </div>
                        </div>
                        <!-- /.box-body -->
                    </div>
                    <!-- /.box -->

                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
    </section>

@stop

resources/views/goods/show.blade.php
@extends('adminlte::page')

@section('title', 'Goods')

@section('content_header')
    <h1>Goods</h1>
@stop

@section('content')
    <div class="box">
        <div class="box-header with-border">
            <h3 class="box-title">{{$good->title}}</h3>
            <a href="{{ url('goods/' . $good->id . '/edit') }}" class=""><i class="fa fa-edit mr-2" aria-hidden="true"></i></a>
            <div class="box-body">
                <p>Description: {{$good->description}}</p>
                <p>Price: {{$good->price}}</p>
                @if($good->photo)
                    <img class="attached-photo" src="{{ url('/') }}{{ $good->photo ? Storage::url("$good->photo") : ''}}" alt="picture">
                @endif
            </div>
        </div>
    </div>
@stop