routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('home1');
//    //return view('welcome');
//});

Route::get('/', 'KentekenController@home');
Route::post('/kenteken/make-pdf', 'KentekenController@makePDF');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => ['permission:admin']], function () {
    Route::resource('users', 'UserController');
    Route::resource('goods', 'GoodController');
    Route::resource('orders', 'OrderController');

    Route::get('statistics/index', 'StatisticsController@index');
    Route::get('statistics/analytics', 'StatisticsController@analytics');
    Route::get('statistics/traffic', 'StatisticsController@traffic');
});

Route::get('/buy', 'BuyController@buy');
Route::get('/buy/cart', 'BuyController@cart');
Route::get('/buy/add-to-cart/{id}', 'BuyController@addToCart');
Route::post('/buy/confirm', 'BuyController@confirm');

Route::get('/pdf', 'KentekenController@pdf');

Route::get('/kenteken/buy-pdf', 'KentekenController@buyPDF');
Route::get('/kenteken/pay-pdf', 'KentekenController@payPDF');
Route::get('/kenteken/show-pdf', 'KentekenController@showPDF');
Route::get('/kenteken/cabinet', 'KentekenController@cabinet');

Route::post('/kenteken/pdfSubmit', 'KentekenController@pdfSubmit');
Route::post('/kenteken/submitBuyPDF', 'KentekenController@submitBuyPDF');
Route::post('/kenteken/submitPayPDF', 'KentekenController@submitPayPDF');
Route::post('/kenteken/show-short-pdf', 'KentekenController@showShortPDF');
Route::get('/kenteken/confirm-mollie', 'KentekenController@confirmMollie');

app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'address',
        'status',
        'user_id'
    ];

    protected $dates = [
        'created_at',
        'updated_at'
    ];

    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function b()
    {
        $order_buys = OrderBuy::select(['buy_id'])
            ->where('order_id', $this->id)
            ->get();

        $buys = [];

        foreach($order_buys as $item) {
            $buys[] = Buy::find($item['buy_id']);
        }

        return $buys;
    }
}

app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Order;

class OrderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $orders = Order::orderBy('id', 'desc')->paginate(24);

        return view('orders.index', [
            'orders' => $orders,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('orders.form', [
            'order' => new Order()
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $order = new Order($request->all());

        $order->save();

        return redirect()->action('OrderController@index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $order = Order::find($id);

        return view('orders.show', [
            'order' => $order
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $order = Order::find($id);

        return view('orders.form', [
            'order' => $order,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $order = Order::find($id);
        $order->update($request->all());

        $order->save();

        return redirect()->action('OrderController@index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $order = Order::find($id);
        $order->delete();
        return redirect()->back();
    }
}

resources/views/orders/form.blade.php
@extends('adminlte::page')

@section('title', 'Orders')

@section('content_header')
    <h1>Orders</h1>
@stop

@section('content')
    <div class="box box-primary">
        @if ($errors->any())
            <ul class="errors">
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        @endif
        <div class="box-header with-border">
            <h3 class="box-title">{{isset($order->id) ? 'Update' : 'Create'}}</h3>
        </div>
        <form action="{{isset($order->id) ? route('orders.update', $order->id) : route('orders.index')}}" method="post" enctype="multipart/form-data">
            {{ csrf_field() }}
            {{ method_field(isset($order->id) ? 'PUT' : 'POST') }}
            <div class="box-body">
                <div class="form-group">
                    <label for="name">Name</label>
                    <input class="form-control" id="name" name="name" value="{{ old('name', $order->name) }}"/>
                </div>
                <div class="form-group">
                    <label for="name">Address</label>
                    <input class="form-control" id="address" name="address" value="{{ old('address', $order->address) }}"/>
                </div>
                <div class="form-group">
                    <label for="name">Status</label>
                    <input class="form-control" id="status" name="status" value="{{ old('status', $order->status) }}"/>
                </div>

            </div>
            <!-- /.box-body -->

            <div class="box-footer">
                <button type="submit" class="btn btn-primary">Create</button>
                <a href="{{url('/orders')}}" class="btn btn-default">Cancel</a>
            </div>
        </form>
    </div>

@stop

resources/views/orders/index.blade.php
@extends('adminlte::page')

@section('title', 'Orders')

@section('content_header')
    <h1>Orders</h1>
@stop

@section('content')
    <section class="content">
        <a href="{{'orders/create'}}" class="btn btn-primary" >Create</a>
        <br/><br/>
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title">Orders</h3>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <div id="example2_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
                            <div class="row"><div class="col-sm-6"></div><div class="col-sm-6"></div></div><div class="row">
                                <div class="col-sm-12">
                                    <table id="example2" class="table table-bordered table-hover table-striped dataTable" role="grid" aria-describedby="example2_info">
                                        <thead>
                                        <tr role="row">
                                            <th>Name</th>
                                            <th>Address</th>
                                            <th>Status</th>
                                            <th>User</th>
                                            <th>Items</th>
                                            <th>Actions</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        {{--<tr>--}}
                                            {{--<form class="form-inline search" id="search" method="get" action="/{{ Request::path() }}">--}}
                                                {{--<td>--}}
                                                    {{--<input type="text" class="form-control" name="searchName" autocomplete="off" placeholder="Name" value="{{Request::input('searchName')}}">--}}
                                                {{--</td>--}}
                                                {{--<td></td>--}}
                                                {{--<td></td>--}}
                                                {{--<td></td>--}}
                                                {{--<td></td>--}}
                                                {{--<td></td>--}}
                                                {{--<input type="submit" hidden>--}}
                                            {{--</form>--}}
                                        {{--</tr>--}}
                                        @foreach($orders as $order)
                                            <tr role="row" class="odd">
                                                <td><a href="{{ url('orders/' . $order->id) }}">{{$order->name}}</a></td>
                                                <td>{{$order->address}}</td>
                                                <td>{{$order->status}}</td>
                                                <td>@if($order->user)
                                                        {{$order->user->name}}
                                                    @endif
                                                </td>
                                                <td>
                                                    @foreach($order->b() as $buy)
                                                        {{$buy->good->title}} {{$buy->count}} <br/>
                                                    @endforeach
                                                </td>
                                                <td width="240">
                                                    <a href="{{ url('orders/' . $order->id) }}" class="btn btn-success btn-sm"><i class="fa fa-edit mr-2" aria-hidden="true"></i>View</a>
                                                    <a href="{{ url('orders/' . $order->id . '/edit') }}" class="btn btn-primary btn-sm"><i class="fa fa-edit mr-2" aria-hidden="true"></i>Update</a>
                                                    <button type="button" class="btn btn-secondary btn-sm" data-toggle="modal" data-target="#delete_{{$order->id}}"><i class="fa fa-trash mr-2" aria-hidden="true"></i>Delete</button>

                                                    <div class="modal fade" id="delete_{{$order->id}}" tabindex="-1" role="dialog" aria-labelledby="modal_{{$order->id}}" aria-hidden="true">
                                                        <div class="modal-dialog" role="document">
                                                            <div class="modal-content">
                                                                <div class="modal-header">
                                                                    <h5 class="modal-title" id="modal_{{$order->id}}">Confirm</h5>
                                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                                        <span aria-hidden="true">&times;</span>
                                                                    </button>
                                                                </div>
                                                                <div class="modal-body">
                                                                    <p>Are you sure you want to delete this item?</p>
                                                                </div>
                                                                <div class="modal-footer">
                                                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                                                                    <form action='{{ route('orders.destroy', $order->id) }}' method="POST" style="display: inline">
                                                                        <input type="hidden" name="_method" value="DELETE">
                                                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                                                        <button type="submit" class="btn btn-danger" style="margin-right: 4px">Confirm</button>
                                                                    </form>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </td>
                                            </tr>
                                        @endforeach
                                        </tbody>
                                    </table>
                                    {{$orders
                                        /*->appends([
                                            'searchName' => Request::get('searchName'),
                                            'searchEmail' => Request::get('searchEmail'),
                                        ])*/
                                        ->links()}}
                                </div>
                            </div>
                        </div>
                        <!-- /.box-body -->
                    </div>
                    <!-- /.box -->

                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
    </section>

@stop

resources/views/orders/show.blade.php
@extends('adminlte::page')

@section('title', 'Orders')

@section('content_header')
    <h1>Orders</h1>
@stop

@section('content')
    <div class="box">
        <div class="box-header with-border">
            <h3 class="box-title">{{$order->name}}</h3>
            <a href="{{ url('orders/' . $order->id . '/edit') }}" class=""><i class="fa fa-edit mr-2" aria-hidden="true"></i></a>
            <div class="box-body">
                <p>Description: {{$order->address}}</p>
                <p>Status: {{$order->status}}</p>

            </div>
        </div>
    </div>
@stop